#!/bin/bash
echo "==================="
python alpaca.py --noise_precmax=3.0 --gamma=0.9&
sleep 1m
python alpaca.py --noise_precmax=3.0 --gamma=0.95&
sleep 1
python alpaca.py --noise_precmax=3.0 --gamma=0.98&
sleep 1m
#
python alpaca.py --noise_precmax=10.0 --gamma=0.9&
sleep 1m
python alpaca.py --noise_precmax=10.0 --gamma=0.95&
sleep 1m
python alpaca.py --noise_precmax=10.0 --gamma=0.98&
sleep 1m
# 
python alpaca.py --noise_precmax=30.0 --gamma=0.90&
sleep 1m
python alpaca.py --noise_precmax=30.0 --gamma=0.95&
sleep 1m
python alpaca.py --noise_precmax=30.0 --gamma=0.98
