#!/bin/bash
echo "==================="
python alpaca.py --learning_rate=1e-2 --noise_precmax=1.0&
sleep 1m
python alpaca.py --learning_rate=1e-3 --noise_precmax=1.0&
sleep 1m
python alpaca.py --learning_rate=1e-4 --noise_precmax=1.0&
sleep 1m
python alpaca.py --learning_rate=1e-2 --noise_precmax=10.0&
sleep 1m
python alpaca.py --learning_rate=1e-3 --noise_precmax=10.0&
sleep 1m
python alpaca.py --learning_rate=1e-4 --noise_precmax=10.0&
sleep 1m
