#!/bin/bash
echo "==================="
#
python alpaca.py --split_ratio=0.4 --split_ratio_max=0.4&
sleep 1m
python alpaca.py --split_ratio=0.6 --split_ratio_max=0.6&
sleep 1m
python alpaca.py --split_ratio=0.75 --split_ratio_max=0.75&
sleep 1m
python alpaca.py --split_ratio=0.9 --split_ratio_max=0.9&
sleep 1m
#
python alpaca.py --update_freq_post=3&
sleep 1m
python alpaca.py --update_freq_post=5&
sleep 1m
python alpaca.py --update_freq_post=8&
sleep 1m
python alpaca.py --update_freq_post=10&
sleep 1m
#
python alpaca.py --hidden_space=64&
sleep 1m
python alpaca.py --hidden_space=128&
sleep 1m
python alpaca.py --latent_space=4&
sleep 1m 
#
python alpaca.py --learning_rate=1e-2&
sleep 1m
python alpaca.py --learning_rate=5e-2
#
#python alpaca.py --L_episode=30&
#sleep 1m
#python alpaca.py --L_episode=40&
#sleep 1m
#python alpaca.py --L_episode=50&
#sleep 1m
#
#python alpaca.py --replay_memory_size=100&
#sleep 1m
#python alpaca.py --replay_memory_size=1000&
#sleep 1m
#python alpaca.py --replay_memory_size=10000
