#!/bin/bash
echo "==================="
python alpaca.py --hidden_space=64 --latent_space=8
python alpaca.py --hidden_space=64 --latent_space=16
python alpaca.py --hidden_space=128 --latent_space=8
python alpaca.py --hidden_space=128 --latent_space=16

python alpaca.py --learning_rate=1e-2
python alpaca.py --learning_rate=5e-3
python alpaca.py --learning_rate=1e-3

python alpaca.py --replay_memory_size=10
python alpaca.py --replay_memory_size=100
python alpaca.py --replay_memory_size=1000

python alpaca.py --update_freq_target=2
python alpaca.py --update_freq_target=5
python alpaca.py --update_freq_target=10
python alpaca.py --update_freq_target=100
