#!/bin/bash
echo "==================="
random_seed1=1234
random_seed2=2345
for latent in 2 4 8
do
	for prior in 0.01 0.5
	do
		for noise in 0.01 0.1 0.5
		do
			python alpaca.py --latent_space=$latent --prior_precision=$prior --noise_precision=$noise --random_seed=$random_seed1 &
			sleep 1m
			python alpaca.py --latent_space=$latent --prior_precision=$prior --noise_precision=$noise --random_seed=$random_seed2
			wait
		done
	done
done
