#!/bin/bash
echo "==================="
python alpaca.py --hidden_space=64 --latent_space=8
python alpaca.py --hidden_space=64 --latent_space=16
python alpaca.py --hidden_space=128 --latent_space=8
python alpaca.py --hidden_space=128 --latent_space=16

python alpaca.py --gamma=0.8
python alpaca.py --gamma=0.95
python alpaca.py --gamma=0.99

python alpaca.py --learning_rate=2e-2
python alpaca.py --learning_rate=5e-2

python alpaca.py --prior_precision=0.05
python alpaca.py --prior_precision=0.5

python alpaca.py --noise_precision=0.1
python alpaca.py --noise_precision=1.0
python alpaca.py --noise_precision=5.0

python alpaca.py --split_ratio=0.25
python alpaca.py --split_ratio=0.3

python alpaca.py --replay_memory_size=8
python alpaca.py --replay_memory_size=16
python alpaca.py --replay_memory_size=32
python alpaca.py --replay_memory_size=64
python alpaca.py --replay_memory_size=128

python alpaca.py --iter_max=3
python alpaca.py --iter_max=5

python alpaca.py --L_episode=20
python alpaca.py --L_episode=30
python alpaca.py --L_episode=40

python alpaca.py --N_tasks=4
python alpaca.py --N_tasks=6
